/** @type {import('typedoc').TypeDocOptions} */
module.exports = {
  entryPoints: ['./src/index.ts'],
  out: 'docs',
  validation: {
    notDocumented: true,
  },
  treatWarningsAsErrors: true,
  excludePrivate: true,
  categoryOrder: [
    'Accumulator',
    'Allocate Receive',
    'Allocate Send',
    'Branch',
    'Commutative',
    'Component',
    'Confirm Native',
    'Confirm Native Proof',
    'Confirm Token',
    'Confirm Token Proof',
    'Constants',
    'Core',
    'Flags',
    'Receive',
    'Receive From',
    'Receive Native',
    'Receive Token',
    'Receive Token From',
    'Refund Native',
    'Refund Native Proof',
    'Refund Token',
    'Refund Token Proof',
    'Send',
    'Send Fail',
    'Send Float',
    'Send Native',
    'Send Native Float',
    'Send Save',
    'Send Token',
    'Send Token Float',
    'Settle',
    'Settle Native',
    'Settle Native Proof',
    'Settle Proof',
    'Settle Token',
    'Settle Token Proof',
    'Tree',
    '*',
  ],
  excludeExternals: true,
  externalPattern: [],
};
