const categories = [
  'Accumulator',
  'Allocate Receive',
  'Allocate Send',
  'Branch',
  'Commutative',
  'Component',
  'Confirm Native',
  'Confirm Native Proof',
  'Confirm Token',
  'Confirm Token Proof',
  'Constants • Allocation',
  'Constants • Event Signature',
  'Constants • Proof Chain',
  'Constants • Receive',
  'Constants • Receive State',
  'Constants • Send',
  'Constants • Send Float',
  'Constants • Send State',
  'Core',
  'Flags',
  'Receive',
  'Receive From',
  'Receive Native',
  'Receive Token',
  'Receive Token From',
  'Refund Native',
  'Refund Native Proof',
  'Refund Token',
  'Refund Token Proof',
  'Send',
  'Send Float',
  'Send Native',
  'Send Native Float',
  'Send Token',
  'Send Token Float',
  'Settle',
  'Settle Native',
  'Settle Native Proof',
  'Settle Proof',
  'Settle Token',
  'Settle Token Proof',
  'Tree',
  '*',
];
export default categories;
